name: Tests

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "21 5 * * 1"
  workflow_dispatch:

jobs:
  # Lint code with pre-commit.
  Linter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit validation
        run: pre-commit run --all-files

  # Run tests with pytest.
  Tests:
    needs: [Linter]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      CODECOV_OS: ${{ matrix.os }}
      CODECOV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      # Prevents scheduled run being disabled after no commit
      # for some time (creates a dummy commit):
      - uses: gautamkrishnar/keepalive-workflow@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # Caching pip dependencies.
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      # - name: Test with pytest (xdist)
      #   if: matrix.os != 'ubuntu-latest'
      #   run: pytest -vvvx -n auto -m "not slow and not extra and not skipci" --durations=50 --cov
      - name: Test with pytest
        run: pytest -vvvx -m "not slow and not extra and not skipci" --durations=50 --cov
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v3
        # Currently we only upload in one of the matrix cases: ubuntu + py38:
        if: (matrix.os == 'ubuntu-latest') && (matrix.python-version == '3.8')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: test  # {test,test_full}
          env_vars: CODECOV_OS,CODECOV_PYTHON
          name: upload_test_${{ matrix.os }}_python${{ matrix.python-version }}
          fail_ci_if_error: false  # Whether CI fails if this step fails.
          os: ${{ runner.os }}
          verbose: true
      # - name: Run doctests with pytest (xdist)
      #   if: matrix.os != 'ubuntu-latest'
      #   run: pytest -vvvx -n auto src/ --doctest-modules --durations=50
      - name: Run doctests with pytest
        run: pytest -vvvx src/ --doctest-modules --durations=50
      - name: Test notebooks run without error
        run: python tests/nb_eval.py --nb_dir ./
