name: "Tests: Dependency Versions"

on:
  schedule:
    # This schedule is monthly.
    - cron: "29 3 12 * *"
  workflow_dispatch:

jobs:
  # Test with the dependency versions specified in the matrix.
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
        dep:
          - torch==1.10
          - torch>=2
          - pandas==1.3
          - pandas>=2
          - numpy==1.20
          - numpy>=1.24
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # Caching pip dependencies.
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[testing]
          pip install "${{ matrix.python-version }}"
      - name: Test with pytest (xdist)
        if: matrix.os != 'ubuntu-latest'
        run: pytest -vvvx -n auto -m "not slow and not extra and not skipci" --durations=50 --cov
      - name: Test with pytest
        if: matrix.os == 'ubuntu-latest'
        run: pytest -vvvx -m "not slow and not extra and not skipci" --durations=50 --cov
